### ISSUE TITLE
CASI MUERO DE SED!

### ISSUE THREAD

**Issue by Ian354** [antipersona/Fuentes-Madrid#1]
Por culpa de tu incompetencia incluyendo fuentes "CERRADAS_TEMPORALMENTE", he visitado varias fuentes cerradas temporalmente. Por favor te pido que corrijas el código y no incluyas dichas fuentes. Gracias un saludo.

**Comment by Ju4Nd123** [comment]
No te preocupes, yo te lo arreglo!
